[six_music]
    verbose_name = "BBC 6 Music"
    url = "https://www.bbc.co.uk/programmes/articles/5JDPyPdDGs3yCLdtPhGgWM7/bbc-radio-6-music-playlist"
    type = "playlist"
[radio1]
    verbose_name = "BBC Radio 1"
    url = "https://www.bbc.co.uk/programmes/articles/3tqPdBWF9yMbTrfjWvfKV8t/radio-1-playlist"
    type = "playlist"
[dance_anthems]
    verbose_name = "BBC Dance Anthems"
    url = "https://www.bbc.co.uk/programmes/m000qj2w"
    type = "show"
